<?php
namespace Business\Model;
use Business\Model\BCommonModel;
class BArticleModel extends BCommonModel{
    //自动验证
    protected $_validate = array(
        //array(验证字段,验证规则,错误提示,验证条件,附加规则,验证时间)
        array('artile_title', 'require', '标题不能为空！', self::MUST_VALIDATE, 'regex', self::MODEL_BOTH),
    );

    protected $_auto = array (
        array('create_time', 'mGetTime', self::MODEL_INSERT, 'callback' ),
        array('update_time', 'mGetTime',self::MODEL_BOTH, 'callback' )
    );

    // 获取当前时间
    public function mGetTime() {
        return time();
    }

    protected function _before_write(&$data) {
        parent::_before_write($data);
    }
    function insert($insert) {
        $insert["company_id"]=get_company_id();
        return parent::insert($insert); // TODO: Change the autogenerated stub
    }

}
