<?php
namespace Business\Model;
use Business\Model\BCommonModel;
use Think\Exception;

class BGoodsPicModel extends BCommonModel{
    function insert($insert) {
        $insert["company_id"]=get_company_id();
        return parent::insert($insert); // TODO: Change the autogenerated stub
    }

    /**
     *商品图片查询（一条）
     * @param $data
     * @return mixed
     * @author dengzs @date 2018/7/6 14:24
     */
    public function pic_handle_findOne($data){
        $where = [
            'id' => $data['id'],
        ];
        return $this->where($where)->find();
    }

    /**
     *商品图片新增
     * @param $data
     * @return mixed
     * @author dengzs @date 2018/7/6 14:24
     */
    public function pic_handle_insert($data){
        $arr = [
            'goods_id' => $data['goods_id'],
            'pic' => $data['filename'],
            'type' => 1,
            'company_id' => get_company_id(),
        ];
        return $this->add($arr);
    }

    /**
     *商品图片删除
     * @param $data
     * @return bool
     * @author dengzs @date 2018/7/6 14:25
     */
    public function pic_handle_del($data){
        $arr = [
            'deleted' => 1,
        ];
        $where = [
            'id' => $data['id'],
        ];
        return $this->where($where)->save($arr);
        /*$res = $this->where($where)->delete();*/
    }
    /**
     *商品图片设置主图
     * @param $data
     * @return bool
     * @author dengzs @date 2018/7/6 14:25
     */
    public function pic_handle_default($data){
        $flag = true;
        $this->startTrans();
        try{
            $res1 = $this->where("goods_id=".$data['goods_id'])->save(array('is_hot'=>0));
            $res2 = $this->where("id=".$data['id'])->save(array('is_hot'=>1));
            $this->commit();
        }catch (Exception $e){
            $this->rollback();
            $flag = false;
        }
        return $flag;
    }

}
