<?php
namespace Business\Model;
use Business\Model\BCommonModel;
class BGoodsPicModel extends BCommonModel{
    function insert($insert) {
        $insert["company_id"]=get_company_id();
        return parent::insert($insert); // TODO: Change the autogenerated stub
    }

    /**
     *商品图片新增
     * @param $data
     * @return mixed
     * @author dengzs @date 2018/7/6 14:24
     */
    public function pic_handle_insert($data){
        $arr = [
            'goods_id' => $data['goods_id'],
            'pic' => $data['filename'],
            'type' => 1,
            'company_id' => get_company_id(),
        ];
        return $this->add($arr);
    }

    /**
     *商品图片删除
     * @param $data
     * @return bool
     * @author dengzs @date 2018/7/6 14:25
     */
    public function pic_handle_del($data){
        $arr = [
            'deleted' => 1,
        ];
        $where = [
            'id' => $data['id'],
        ];
        return $this->where($where)->save($arr);
        /*$res = $this->where($where)->delete();*/
    }
    /**
     *商品图片设置主图
     * @param $data
     * @return bool
     * @author dengzs @date 2018/7/6 14:25
     */
    public function pic_handle_default($data){
        $goods_id = $this->where("id='".$data['id']."'")->getField('goods_id');
        $res = $this->where("goods_id=".$goods_id)->save(array('is_hot'=>0));
        if ($res){
            $arr = [
                'id' => $data['id'],
                'is_hot' => 1,
            ];
            return $this->save($arr);
        }else{
            return false;
        }

    }

}
