<?php
namespace Business\Model;
use Business\Model\BCommonModel;
class BOutboundDetailModel extends BCommonModel{
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->bproduct_model=D("BProduct");
    }
    //通过调拨单id获取调拨明细与其详细信息
    public function getList_detail($allot_id){
        if($allot_id){
            $condition=array("outbound_id"=>$allot_id,"boutbounddetail.deleted"=>0);
        }else{
            $condition=array("boutbounddetail.deleted"=>0);;
        }
        $join="left join ".DB_PRE."b_product bproduct on bproduct.id=boutbounddetail.p_id";
        $join.=$this->bproduct_model->get_product_join_str();
        $field="boutbounddetail.*,bproduct.goods_id,bproduct.type,bproduct.product_code";
        $field.=$this->bproduct_model->get_product_field_str(3);
        $detail_data=$this->alias("boutbounddetail")->getList($condition,$field,$limit="",$join,$order='boutbounddetail.id desc');
        foreach($detail_data as $k=>$v){
            $detail_data[$k]["product_detail"]=strip_tags($this->bproduct_model->get_product_detail_html($v));
            $detail_data[$k]["product_pic"]=$this->bproduct_model->get_goods_pic($v['photo_switch'],$v['goods_id'],$v['p_id']);
        }
        return $detail_data;
    }
    //通过调拨单id获取调拨明细与其详细信息
    public function new_getList_detail($where){
        $condition=array("boutbounddetail.deleted"=>0);
        if($where){
            $condition=array_merge($condition,$where);
        }
        $join="  join ".DB_PRE."b_outbound_order boutbound on boutbounddetail.outbound_id=boutbound.id";
        $join.=" left join ".DB_PRE."b_product bproduct on bproduct.id=boutbounddetail.p_id";
        $join.=" left join ".DB_PRE."b_employee  create_musers on create_musers.user_id=boutbound.user_id and create_musers.deleted=0 and create_musers.company_id=boutbound.company_id";
        $join.=" left join ".DB_PRE."b_employee  check_musers on check_musers.user_id=boutbound.check_id  and check_musers.deleted=0 and check_musers.company_id=boutbound.company_id";
        /*$join.=" left join ".DB_PRE."m_users create_musers on create_musers.id=boutbound.user_id";
        $join.=" left join ".DB_PRE."m_users check_musers on check_musers.id=boutbound.check_id";*/
        $field="boutbound.*,create_musers.employee_name user_nicename,check_musers.employee_name check_name";
        $detail_data=$this->alias("boutbounddetail")->getList($condition,$field,$limit="",$join,$order='boutbounddetail.id desc');

        return $detail_data;
    }

}
