<?php
namespace Business\Model;
use Business\Model\BCommonModel;
class BSellRecoveryProductModel extends BCommonModel{
    
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->bproduct_model=D("BProduct");
    }

    public function getProductList($sell_id = 0){
    	$where = array(
    		's.company_id'=> get_company_id(),
    		's.sell_id'=> $sell_id,
			's.deleted'=> 0
    	);
    	$field = 's.*, p.product_code, g.goods_name, gc.goods_name as goodsname, g.goods_spec';
    	$join = ' LEFT JOIN '.C('DB_PREFIX').'b_product as p ON (p.product_code = s.product_code)';
    	$join .= ' LEFT JOIN '.C('DB_PREFIX').'b_goods as g ON (g.id = p.goods_id)';
    	$join .= ' LEFT JOIN '.C('DB_PREFIX').'b_goods_common as gc ON (gc.id = g.goods_common_id)';
    	$list = $this->alias('s')->getList($where, $field, null, $join);
    	return $list;
    }

	/**
	 * 检测以旧换新信息和截金信息的编号在以旧换新表中是否存在
	 * @param $recovery_old_products
	 * @return mixed
	 */
	function check_rproduct_code($recovery_products,$recovery_old_products){
		$recovery_old_products=empty($recovery_old_products)?array():$recovery_old_products;
		$recovery_products=empty($recovery_products)?array():$recovery_products;
		$new_recovery_product=array_merge($recovery_old_products,$recovery_products);
		if($new_recovery_product){
			$r_rproduct_code=array_column($new_recovery_product, 'rproduct_code');
			$r_rproduct_id=array_column($recovery_old_products, 'old_product_id');
			$condition=array('company_id'=>get_company_id(),'deleted'=>0);
			$condition['rproduct_code']=array('in',$r_rproduct_code);
			if(!empty($r_rproduct_id)) {
				$condition['id'] = array('not in',$r_rproduct_id);
			}
			$is_r_exsit_code=M("BSellRecoveryProduct")->where($condition)->getField('rproduct_code',true);
			//判断以旧换新是否存在了金料编号
			if(!empty($r_rproduct_code)&&!empty($is_r_exsit_code)){
				$info['status'] = 0;
				$info['msg']='以旧换新：货品编号('.implode(',',array_unique($is_r_exsit_code)).')已经存在';
				return $info;
			}
		}
		$info['status'] = 1;
		$info['msg']='不存在相同信息';
		return $info;
	}
}
