<?php
namespace Business\Model;
use Business\Model\BCommonModel;
class BWprocureDetailModel extends BCommonModel{
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->bwgoods_model=D("BWgoods");
    }

    //自动验证
    protected $_validate = array(
        //array(验证字段,验证规则,错误提示,验证条件,附加规则,验证时间)
       // array('sector_id', 'require', '部门不能为空！', 1, 'regex', BCommonModel:: MODEL_BOTH ),
    );
    //自动完成
    protected $_auto = array(
        //array(填充字段,填充内容,填充条件,附加规则)
    );
    //通过调拨单id获取调拨明细与其详细信息
    public function getList_detail($where){
        $condition=array("bwprocuredetail.deleted"=>0);
        if(!empty($where)){
            $condition=array_merge($condition,$where);
        }
        $join="left join ".DB_PRE."b_wgoods bwgoods on bwgoods.id=bwprocuredetail.wgoods_id";
        $field="bwprocuredetail.*,bwgoods.goods_name,bwgoods.goods_code,bwgoods.goods_spec,bwgoods.goods_unit,bwgoods.price_mode";
        $detail_data=$this->alias("bwprocuredetail")->getList($condition,$field,$limit="",$join,$order='bwprocuredetail.id desc');
        foreach($detail_data as $k=>$v){
            $detail_data[$k]["product_pic"]=$this->bwgoods_model->get_goods_pic($v['wgoods_id']);
        }
        return $detail_data;
    }
}
