<?php
namespace Business\Model;
use Business\Model\BCommonModel;
class BWsellDetailModel extends BCommonModel{
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->bwgoods_model=D("BWgoods");
    }
    public function getList_detail($sell_id){
        if($sell_id){
            $condition=array("wsell_id"=>$sell_id);
        }else{
            $condition="";
        }
        $join="left join ".DB_PRE."b_wgoods bwgoods on bwgoods.id=bwselldetail.wgoods_id";
       // $join.=$this->bwgoods_model->get_product_join_str();
        $field="bwselldetail.*,bwgoods.goods_code,bwgoods.goods_name,bwgoods.sell_pricemode";
       // $field.=$this->bwgoods_model->get_product_field_str();
        $detail_data=$this->alias("bwselldetail")->getList($condition,$field,$limit="",$join,$order='bwselldetail.id desc');
        foreach($detail_data as $k=>$v){
            $detail_data[$k]["product_pic"]=$this->bwgoods_model->get_goods_pic($v['wgoods_id']);
       }
        return $detail_data;
    }
}
